### ISSUE TITLE
Resource File Topic

### ISSUE THREAD

**Issue by jtom38** [jtom38/PowerManager#4]
The file that will track all the dependencies needs to have the schema defined and also define how to store the file on disk.

Yaml is a nice format but not native to PowerShell.  We would have to use a module to support it.
Json is native to PowerShell but less human friendly, but easy to Import/Export.
psd1 is native to Powershell to import but exporting them would require more research or custom code.

@todiorne  thoughts?  We should pick something and stick with it to avoid breaking changes.

**Comment by todiorne** [comment]
@jtom38 - lets go with json. Less human friendly yes, but more universal and I like that.

**Comment by jtom38** [comment]
Sounds good. We can work with hash tables in memory and export json.
